# Generated by Django 5.2.5 on 2025-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuario_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.CharField(blank=True, choices=[('A FAZER', 'A fazer'), ('FAZENDO', 'Fazendo'), ('FEITO', 'Feito')], null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], null=True),
        ),
    ]
