# Generated by Django 5.2.5 on 2025-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tarefas_status_alter_tarefas_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(blank=True, choices=[('A FAZER', 'A fazer'), ('FAZENDO', 'Fazendo'), ('FEITO', 'Feito')], default='A FAZER', null=True),
        ),
    ]
